---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r}
library(ggplot2)
library(lubridate)
rawdata <- read.csv("activity.csv");
rawdata$date <- ymd(rawdata$date)
completedata <- rawdata[complete.cases(rawdata),]

```


## What is mean total number of steps taken per day?
```{r}
totalStepsPerDay <- aggregate(steps~date,completedata,sum)
totalDays = dim(totalStepsPerDay)[[1]]
hist(totalStepsPerDay$steps,breaks=totalDays,main="Histogram of steps per day",col="red",xlab="Days",ylab="Steps")

##Mean and median per day
meansteps <- mean(totalStepsPerDay$steps)
mediansteps <- median(totalStepsPerDay$steps)

```
mean of total steps per day  `r meansteps`  
median of total steps per day  `r mediansteps`


## What is the average daily activity pattern?
```{r}

intervalBasedAvg <- aggregate(steps~interval,completedata,mean)
g <- ggplot(intervalBasedAvg,aes(x=interval,y=steps)) + geom_line();
g <- g + labs(x="interval",y="average steps")
g <- g + ggtitle("Average steps over intervals")
print(g)

maxAvg <- max(intervalBasedAvg$steps)

```
The maximum average over intervals is `r maxAvg`

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?
